# Generated by Django 4.2.5 on 2023-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_teammembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='member_image',
            field=models.ImageField(upload_to='members'),
        ),
    ]
